"""HTML report output (self-contained)."""

from __future__ import annotations

from pathlib import Path

import aiofiles

from prowl.models.report import CrawlReport
from prowl.models.target import Endpoint, Secret


class HtmlOutput:
    """Generate a self-contained HTML report."""

    def __init__(self, output_dir: str) -> None:
        self._dir = Path(output_dir)
        self._dir.mkdir(parents=True, exist_ok=True)
        self._endpoints: list[Endpoint] = []
        self._secrets: list[Secret] = []

    async def write_endpoint(self, endpoint: Endpoint) -> None:
        self._endpoints.append(endpoint)

    async def write_secret(self, secret: Secret) -> None:
        self._secrets.append(secret)

    async def finalize(self, report: CrawlReport | None = None) -> None:
        path = self._dir / "report.html"
        r = report

        # Build endpoint rows
        ep_rows = ""
        for ep in self._endpoints[:1000]:
            tags = " ".join(f'<span class="tag">{t}</span>' for t in ep.tags)
            ep_rows += f"""<tr>
                <td><code>{ep.method}</code></td>
                <td class="url">{_esc(ep.url)}</td>
                <td>{ep.status_code or '-'}</td>
                <td>{ep.source_module}</td>
                <td>{ep.param_count}</td>
                <td>{tags}</td>
            </tr>"""

        secret_rows = ""
        for s in self._secrets:
            val = _esc(s.value[:40])
            secret_rows += f"""<tr>
                <td>{s.kind}</td>
                <td class="url">{_esc(s.source_url)}</td>
                <td><code>{val}</code></td>
            </tr>"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Prowl Report - {_esc(r.target) if r else 'N/A'}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:Inter,-apple-system,sans-serif;background:#0f1117;color:#e4e5e9;padding:24px}}
h1{{color:#3b82f6;margin-bottom:8px}}
h2{{color:#9ca0b0;margin:24px 0 12px;font-size:18px}}
.stats{{display:flex;gap:16px;margin:16px 0}}
.stat{{background:#1a1d27;padding:12px 20px;border-radius:8px;border:1px solid #2e3144}}
.stat .val{{font-size:24px;font-weight:700;color:#3b82f6}}
.stat .lbl{{font-size:12px;color:#6b7084}}
table{{width:100%;border-collapse:collapse;margin:8px 0;font-size:13px}}
th{{text-align:left;padding:8px;background:#1a1d27;color:#9ca0b0;border-bottom:1px solid #2e3144}}
td{{padding:6px 8px;border-bottom:1px solid #1a1d27}}
.url{{font-family:monospace;font-size:12px;word-break:break-all;max-width:500px}}
.tag{{font-size:10px;padding:2px 6px;background:#242736;border-radius:8px;margin-right:4px}}
code{{background:#242736;padding:2px 6px;border-radius:4px;font-size:12px}}
</style>
</head>
<body>
<h1>Prowl Crawl Report</h1>
<p>Target: <code>{_esc(r.target) if r else 'N/A'}</code> &middot; Duration: {f'{r.scan_duration:.1f}s' if r else ''}</p>

<div class="stats">
    <div class="stat"><div class="val">{len(self._endpoints)}</div><div class="lbl">Endpoints</div></div>
    <div class="stat"><div class="val">{sum(e.param_count for e in self._endpoints)}</div><div class="lbl">Parameters</div></div>
    <div class="stat"><div class="val">{len(self._secrets)}</div><div class="lbl">Secrets</div></div>
</div>

<h2>Endpoints</h2>
<table>
<tr><th>Method</th><th>URL</th><th>Status</th><th>Source</th><th>Params</th><th>Tags</th></tr>
{ep_rows}
</table>

{"<h2>Secrets</h2><table><tr><th>Kind</th><th>Source</th><th>Value</th></tr>" + secret_rows + "</table>" if self._secrets else ""}

<p style="margin-top:32px;color:#6b7084;font-size:12px">Generated by Prowl</p>
</body></html>"""

        async with aiofiles.open(path, "w", encoding="utf-8") as f:
            await f.write(html)


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
