"""Markdown report output."""

from __future__ import annotations

from pathlib import Path

import aiofiles

from prowl.models.report import CrawlReport
from prowl.models.target import Endpoint, Secret


class MarkdownOutput:
    """Generate a Markdown crawl report."""

    def __init__(self, output_dir: str) -> None:
        self._dir = Path(output_dir)
        self._dir.mkdir(parents=True, exist_ok=True)
        self._endpoints: list[Endpoint] = []
        self._secrets: list[Secret] = []

    async def write_endpoint(self, endpoint: Endpoint) -> None:
        self._endpoints.append(endpoint)

    async def write_secret(self, secret: Secret) -> None:
        self._secrets.append(secret)

    async def finalize(self, report: CrawlReport | None = None) -> None:
        path = self._dir / "report.md"
        r = report

        lines = [
            f"# Prowl Crawl Report",
            "",
            f"**Target:** {r.target if r else 'N/A'}",
            f"**Duration:** {r.duration_seconds:.1f}s" if r else "",
            f"**Endpoints:** {len(self._endpoints)}",
            f"**Secrets:** {len(self._secrets)}",
            "",
            "---",
            "",
            "## Endpoints",
            "",
            "| Method | URL | Status | Source | Params |",
            "|--------|-----|--------|--------|--------|",
        ]

        for ep in self._endpoints[:500]:
            url_short = ep.url[:80]
            lines.append(
                f"| {ep.method} | `{url_short}` | {ep.status_code or '-'} "
                f"| {ep.source_module} | {ep.param_count} |"
            )

        if self._secrets:
            lines.extend([
                "",
                "---",
                "",
                "## Secrets",
                "",
                "| Kind | Source | Value (truncated) |",
                "|------|--------|-------------------|",
            ])
            for s in self._secrets:
                val = s.value[:30] + "..." if len(s.value) > 30 else s.value
                lines.append(f"| {s.kind} | `{s.source_url[:60]}` | `{val}` |")

        if r and r.module_reports:
            lines.extend([
                "",
                "---",
                "",
                "## Module Summary",
                "",
                "| Module | Endpoints | Requests | Errors | Duration |",
                "|--------|-----------|----------|--------|----------|",
            ])
            for mr in r.module_reports:
                lines.append(
                    f"| {mr.module_name} | {mr.endpoints_found} "
                    f"| {mr.requests_made} | {mr.errors} "
                    f"| {mr.duration_seconds:.1f}s |"
                )

        lines.extend(["", "---", "", "*Generated by Prowl*", ""])

        async with aiofiles.open(path, "w") as f:
            await f.write("\n".join(lines))
